### ISSUE TITLE
Compact JSON-LD task and STORE_NODE action

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#29]
The `COMPACT_JSONLD` task should run a compact operation on the retrieved JSON input and then produce a STORE_NODE action with the result. 

STORE_NODE action:
```py
{
  'type': 'STORE_NODE',
  'node_id': 'https://example.com/assertionmaybe',
  'data': {"@context": "https://w3id.org/openbadges/v2", ...}
}
```

**Comment by ViktorHaag** [comment]
In order to get pyld to be able to load the @context document for openbadges where it currently resides, it looks like we need a technique as included in commit cebc002a0cbb04aa4627c91079b354b96e223ddf to build a specialized document_loader that uses requests library instead of urllib3.

Is it appropriate to add back in the document loader utility from that commit, or is it more appropriate to ensure that the openbadges context document can be fetchable with clients using the basic pyld library?

**Comment by ViktorHaag** [comment]
At the moment, we seem to have `ADD_NODE` and `UPDATE_NODE` actions; do we believe that this issue requires the new task to produce an `ADD_NODE` action?

**Comment by ottonomy** [comment]
Yes, indeed the jsonld_compact_node task should return an actions list of: 
```py
[add_task(ADD_NODE, data=compact_jsonld_string)]
```

We can refactor in the future if there's ever a case where we want to compact data without adding the result as a new node.

Let me know if you want me to pick this one up. I'll get started on the next pieces in a little bit but will loop back around for this one.

**Comment by ViktorHaag** [comment]
This one is superceded by PR #40, so I'm going to close this issue.

**Comment by mgylling** [comment]
Done in #40.
